controllers:
  - name: eval-based-stopback-controller
    controller-metrics:
      - name: embc
        handler-class: EvalMetricBasedControl
    triggers:
      - on_evaluate
    control-operations:
      should_training_stop: True
    rule: embc["early_stopping_patience_counter"] >= embc["early_stopping_patience"]