controllers:
  - name: loss-controller
    controller-metrics:
      - name: wsl
        handler-class: WindowStepLoss
        arguments:
          window_size: 3
    triggers:
      - on_step_end
    control-operations:
      should_training_stop: True
    rule: wsl["consistently_increasing"] == 1