controller-metrics:
  - name: wsl
    handler-class: StepLoss
    arguments:
      window_size: 3
controllers:
  - name: loss-controller
    triggers:
      - on_step_end
    control-operations:
      should_training_stop: True
    rule: wsl["consistently_increasing"] == 1