controller-metrics:
  - name: elc
    handler-class: EpochLoss
    arguments:
      window_size: 2
controllers:
  - name: epoch-loss-controller
    triggers:
      - on_epoch_end
    control-operations:
      should_training_stop: True
    rule: elc['final_loss'][-1] > elc['final_loss'][-2]