# Copyright The FMS HF Tuning Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Standard
import json
import os

# Third Party
from aim.hugging_face import AimCallback  # pylint: disable=import-error
from transformers.utils import logging

# Local
from .tracker import Tracker
from tuning.config.tracker_configs import AimConfig

AIM_HASH_EXPORT_FILENAME = "aim_run_hash.json"


class CustomAimCallback(AimCallback):
    """
    Custom Aimstack callback is used to export run id from Aim
    as soon as it is created, which is during on_init_end.
    """

    # path where we export run hash generated by Aim
    # This is used to link back to the expriments from outside aimstack
    run_id_export_path = None
    logger = None

    def on_init_end(self, args, state, control, **kwargs):
        # pylint: disable=unused-argument
        """
        Override Aimstack callback on_init_end function
        First call AimCallback.setup to initialize internal structures
        second export Aimstack's run hash to a file
        hash is exported to, AimConfig.aim_run_id_export_path if it is passed
        or, training_args.output_dir/aim_run_hash.json if output_dir is present
        Exported hash looks like '{"run_hash":"<hash>"}' in the file
        hash is not exported if both paths are invalid
        """
        self.setup()  # initialize aim's run_hash

        # Store the run hash
        # Change default run hash path to output directory
        if self.run_id_export_path is None:
            if args and args.output_dir:
                # args.output_dir/aim_run_hash
                self.run_id_export_path = os.path.join(
                    args.output_dir, AIM_HASH_EXPORT_FILENAME
                )

        if self.run_id_export_path is None:
            self.logger.error(
                "To export Aimstack hash either output_dir \
                                or aim_run_id_export_path should be set"
            )

        if self.run_id_export_path:
            if not os.path.isfile(self.run_id_export_path):
                raise FileNotFoundError(
                    "Aimstack hash export path {}\
                                         doesn't exist!".format(
                        self.run_id_export_path
                    )
                )
            with open(self.run_id_export_path, "w", encoding="utf-8") as f:
                run_hash_obj = {"run_hash": str(self.experiment.hash)}
                data = json.dumps(run_hash_obj)
                f.write(data)


class AimStackTracker(Tracker):
    def __init__(self, tracker_config: AimConfig):
        """
        Tracker which uses Aimstack to collect and store metrics.
        """
        super().__init__(name="aim", tracker_config=tracker_config)
        self.logger = logging.get_logger("aimstack_tracker")

    def get_hf_callback(self):
        """
        Returns the aim.hugging_face.AimCallback object associated with this tracker.
        """
        c = self.config
        exp = c.experiment
        url = c.aim_url
        repo = c.aim_repo
        run_id_path = c.aim_run_id_export_path

        if url is not None:
            aim_callback = CustomAimCallback(repo=url, experiment=exp)
        if repo:
            aim_callback = CustomAimCallback(repo=repo, experiment=exp)
        else:
            self.logger.warning(
                "Aim tracker requested but repo or server is not specified. "
                + "Please specify either aim repo or aim server ip and port for using Aim."
            )
            aim_callback = None

        if aim_callback is not None:
            aim_callback.hash_export_path = run_id_path

        # let callback use the tracker logger
        aim_callback.logger = self.logger

        self.hf_callback = aim_callback
        return self.hf_callback

    def track(self, metric, name, stage="additional_metrics"):
        """
        Track any additional `metric` with `name` under Aimstack tracker.
        Expects metric and name to not be None.
        stage can be used to pass the metadata associated with metric,
        like, training metric or eval metric or additional metric
        """
        if metric is None or name is None:
            self.logger.warning("Tracked metric value or name should not be None")
            return
        context = {"subset": stage}
        callback = self.hf_callback
        run = callback.experiment
        if run is not None:
            run.track(metric, name=name, context=context)

    def set_params(self, params, name="extra_params"):
        """
        Attach any extra params with the run information stored in Aimstack tracker.
        Expects params to be a dict of k:v pairs of parameters to store.
        name represents the namespace under which parameters will be associated in Aim.
        """
        if params is None:
            return
        callback = self.hf_callback
        run = callback.experiment
        if run is not None:
            for key, value in params.items():
                run.set((name, key), value, strict=False)
