# This file holds a list of scenarios to may be run.
# - to limit to a number of scenarios, use the --run-only-scenarios flag.
# - Each scenario will be run against a particular acceleration framework
#   config, if the framework_config: key is specified.
#   * a particular framework configuration
# - the arguments tag will hold arguments to be passed to sft_trainer
#   * the arguments are singular except for model_name_or_path which can handle
#     multiple arguments.
# - So anything that is critical for the scenario MUST be specified here 
#   and not in the defaults, e.g. fp16

# This stanza will be used in future to replace the custom processing functions in data_processing.py 
# data_processing:
#   dataset_name: yahma/alpaca-cleaned
#   chat_template: |
#     {%- for message in messages %}
#         {% if message['input'] != '' %}
#     Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

#         {% else %}
#     Below is an instruction that describes a task. Write a response that appropriately completes the request.

#         {% endif %}
#     ### Instruction:
#     {{ message['instruction'] }}

#         {% if message['input'] != '' %}
#     ### Input:
#     {{ message['input'] }}

#         {% endif %}
#     ### Response:
#     {{ message['output'] + eos_token }}
#     {% endfor %}
#   tokenize: True


scenarios:
    -   name: full-finetuning
        framework_config: 
            - 
            - foak-fast-kernels
        arguments:
            learning_rate: 2e-5
            model_name_or_path: 
                - 'ibm/PowerLM-3b'
            torch_dtype: bfloat16

    -   name: standard-peft
        framework_config: 
            - 
            - foak-fast-kernels
        arguments:
            learning_rate: 2e-4
            torch_dtype: bfloat16
            peft_method: lora
            r: 16
            lora_alpha: 16
            lora_dropout: 0.1
            target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
            model_name_or_path: 
                - 'ibm/PowerLM-3b'

    -   name: baseline-peft-bnb
        framework_config: 
            - baseline-peft-bnb
        arguments:
            bf16: True
            learning_rate: 2e-4
            torch_dtype: bfloat16
            peft_method: lora
            r: 16
            lora_alpha: 16
            lora_dropout: 0.1
            target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
            model_name_or_path: 
                - 'ibm/PowerLM-3b'

    -   name: accelerated-peft-bnb
        framework_config: 
            - accelerated-peft-bnb
            - accelerated-peft-bnb-foak
        arguments:
            bf16: True
            learning_rate: 2e-4
            torch_dtype: bfloat16
            peft_method: lora
            r: 16
            lora_alpha: 16
            lora_dropout: 0.1
            target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
            model_name_or_path: 
                - 'ibm/PowerLM-3b'

    # when ready to add this to bench uncomment
    # -   name: accelerated-peft-gptq
    #     framework_config: 
    #         - accelerated-peft-autogptq
    #         - accelerated-peft-autogptq-foak
    #     arguments:
    #         learning_rate: 2e-4
    #         fp16: True # running gptq-lora in float16 is more performant, see issue
    #         torch_dtype: float16 # https://github.com/foundation-model-stack/fms-acceleration/issues/84
    #         peft_method: lora
    #         r: 16
    #         lora_alpha: 16
    #         lora_dropout: 0.1
    #         target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
    #         model_name_or_path: 
    #             - 'ibm/PowerLM-3b'

    -   name: accelerated-moe
        framework_config: 
            - # without acceleration
            - moe-scattermoe-granite
            # add pf
        slow: True
        arguments:
            learning_rate: 5e-5
            torch_dtype: bfloat16
            gradient_accumulation_steps: 16
            logging_steps: 1
            packing: False
            adam_epsilon: 1e-8
            model_name_or_path: 
                - 'ibm/PowerMoE-3b'
