# Copyright The FMS HF Tuning Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Publish FMS-hf-tuning Library

on:
    release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - setup: "3.11"
            tox: "py311"

    environment:
      name: pypi
      url: https://pypi.org/p/fms-hf-tuning
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version.setup }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version.setup }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tox
      - name: Build and test with tox
        run: tox -e ${{ matrix.python-version.tox }}
      - name: Build and check wheel package
        run:
          tox -e build,twinecheck
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
